---
- name: Create a restart script
  template:
    src: ifupdown_restart_script.sh.j2
    dest: /tmp/restart_interfaces.sh
    mode: 0755

- name: Execute Network Restart
  shell: |
    sh /tmp/restart_interfaces.sh
  ignore_errors: yes

- name: debug pause after restart script is executed
  pause:
  when: lookup('env', 'TEST_PAUSE') | bool

- name: Cleanup Network Restart script
  file:
    path: /tmp/restart_interfaces.sh
    state: absent
