---

- name: Update apt cache
  apt:
    cache_valid_time: 600

- name: Install the required packages in Debian derivatives
  apt:
    name: "{{ network_pkgs }}"
    state: present
  environment: "{{ env }}"
  when: network_check_packages
    
- name: Template interfaces file
  template:
    src: ifupdown_interfaces_main.j2
    dest: /etc/network/interfaces
  when: network_configured_interfaces_only | bool
  notify: network_interface__handler_restart_networking
  register: p

- set_fact:
    network_interface__configuration_changed: true
  when: p is changed

- name: Make sure the source include line is there in interfaces file
  lineinfile:
    regexp: '^source\s+{{ net_path | regex_escape() }}'
    line: "source {{ net_path }}/*"
    dest: /etc/network/interfaces
    state: present
    insertafter: EOF
  when: not network_configured_interfaces_only | bool
  
# 'source-directory' includes all files inside the directory, see "man 5 interfaces"
- name: Make sure the source-directory include line is not there in interfaces file
  lineinfile:
    regexp: '^source-directory\s+{{ net_path | regex_escape() }}/?'
    dest: /etc/network/interfaces
    state: absent
  when: not network_configured_interfaces_only | bool

- name: Create the directory for interface cfg files
  file:
    path: "{{ net_path }}"
    state: directory
