# - name: Get all device names
#   set_fact:
#     network_interface__managed_devices: "{{ network_interface__managed_devices | default([]) + [ item['device'] ] | unique }}"
#   loop: >-
#     {{ network_loopback_interfaces
#        + network_ether_interfaces
#        + network_bond_interfaces
#        + network_vlan_interfaces
#        + network_bridge_interfaces }}

- name: Remove all includes in single configuration file mode
  block:
    - find:
        paths: "{{ network_interface_ifupdown_net_path }}"
      register: files_to_remove

    - file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_remove.files }}"
  when:
    - network_interface_single_configuration_file



# - name: Find interface config files to delete
#   find:
#     paths: "{{ network_interface_ifupdown_net_path }}"
#     excludes: >
#       {{ [ network_interface_file_prefix ]
#          | product(network_interface__managed_devices)
#          | map('join', '')
#          | list
#          | product([ network_interface_file_postfix ])
#          | map('join', '')
#          | list if network_interface__managed_devices | default([])
#                 else [] }}
#   register: config_files_to_delete

# - name: Remove all interfaces config files not matching the pattern
#   file:
#     path: "{{ item.path }}"
#     state: absent
#   with_items: "{{ config_files_to_delete.files }}"
#   register: network_interface_register_clean_interfaces
#   notify: network_interface__handler_restart_networking
