---
# Install packages

- name: Update apt cache
  apt:
    cache_valid_time: 600

- name: Install the required packages in Debian derivatives
  apt:
    name: "{{ network_interface_ifupdown_packages }}"
    state: present
  environment: "{{ env }}"
  when:
    - network_check_packages
    - ansible_os_family == "Debian"

# Template main configuration file
# This file contains only minimal configuration for included files
# or all settings if `network_interface_single_configuration_file` is enabled

- name: Template interfaces file
  template:
    src: ifupdown_interfaces_main.j2
    dest: /etc/network/interfaces
  when: network_interface_configured_only | bool
  notify: network_interface__handler_restart_networking
  register: p

- set_fact:
    network_interface__configuration_changed: true
  when: p is changed

- name: Select all managed interfaces as changed when using single file configuration mode
  set_fact:
    network_interface__all_changed_interfaces: >-
      {{ ( network_loopback_interfaces
         + network_ether_interfaces
         + network_vlan_interfaces
         + network_bond_interfaces ) | map(attribute='device') | list | unique }}
  when:
    - p is changed
    - network_interface_single_configuration_file

# Template separate configuration files for interfaces

- name: Create the directory for interface configuration files
  file:
    path: "{{ network_interface_ifupdown_net_path }}"
    state: directory
  when:
    - not network_interface_single_configuration_file

- include_tasks: "ifupdown_remove_configuration.yaml"

- name: Configure Loopback interfaces
  include_tasks: "ifupdown_loopback_interfaces.yaml"

- name: Configure Ethernet interfaces
  include_tasks: "ifupdown_ethernet_interfaces.yaml"

- name: Configure Bond interfaces
  include_tasks: "ifupdown_bond_interfaces.yaml"

- name: Configure VLAN interfaces
  include_tasks: "ifupdown_vlan_interfaces.yaml"

- name: Configure Bridge interfaces
  include_tasks: "bridge_interfaces.yml"
  when: network_bridge_interfaces | length > 0

- set_fact:
    network_interface__all_changed_interfaces: >-
      {{ network_interface__all_changed_interfaces | default([])
         + network_interface__loopback_changed
         + ether_interfaces_changed
         + vlan_interfaces_changed
         + bond_interfaces_changed | sort | unique }}

- set_fact:
    network_interface__configuration_changed: "{{ network_interface__all_changed_interfaces | length > 0 }}"
  



