- name: Remove all includes in single configuration file mode
  block:
    - find:
        paths: "{{ network_interface_ifupdown_net_path }}"
      register: p

    - file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ p.files }}"
  when:
    - network_interface_single_configuration_file

- name: Register managed interfaces
  set_fact:
    _network_interface_managed_interfaces: |-
      {%- set lst = [] -%}
      {%- for type in network_interface -%}
      {%-   for interface in network_interface[type] -%}
      {%-     set _ = lst.append(interface.device) -%}
      {%-   endfor -%}
      {%- endfor -%}
      {{ lst }}

- block:
    
    - name: Find interface config files to delete
      find:
        paths: "{{ network_interface_ifupdown_net_path }}"
        excludes: >
          {{ [ network_interface_file_prefix ]
          | product(_network_interface_managed_interfaces)
          | map('join', '')
          | list
          | product([ network_interface_file_postfix ])
          | map('join', '')
          | list if _network_interface_managed_interfaces | default([])
          else [] }}
      register: p

    - name: Remove all interfaces config files not matching the pattern
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ p.files }}"
  when: >-
    not network_interface_single_configuration_file
      
