---
- name: Create configuration files for vlan devices
  template:
    src: "ifupdown_interface_vlan.j2"
    dest: "{{ network_interface_ifupdown_net_path }}/{{ network_interface_file_prefix }}{{ item.device }}{{ network_interface_file_postfix }}"
  loop: "{{ network_interface['vlans'] }}"
  register: p
  notify: network_interface__handler_restart_networking

- name: Save changed vlan interfaces
  set_fact:
    _network_interface_changed_vlans: >
      {{ p.results | default([])
           | selectattr('changed')
           | map(attribute='item.device')
           | list }}

- debug:
    var: _network_interface_changed_vlans
