- name: Create the network configuration files for loopback interfaces
  template:
    src: "ifupdown_interface_loopback.j2"
    dest: "{{ network_interface_ifupdown_net_path }}/{{ network_interface_file_prefix }}{{ item.device }}{{ network_interface_file_postfix }}"
  loop: "{{ network_interface['loopbacks'] }}"
  register: p
  notify: network_interface__handler_restart_networking

- name: Save changed loopback interfaces
  set_fact:
    _network_interface_changed_loopbacks: >-
      {{ p.results | default([])
         | selectattr('changed')
         | map(attribute='item.device')
         | list }}

- name: Display changed loopback interfaces
  debug:
    var: _network_interface_changed_loopbacks
  
