- name: Create the network configuration files for loopback interfaces
  template:
    src: "interface_loopback_{{ ansible_os_family }}.j2"
    dest: "{{ net_path }}/{{ network_interface_file_prefix }}{{ item.device }}{{ network_interface_file_postfix }}"
  loop: "{{ network_loopback_interfaces }}"
  when:
    - item.device | trim != ""
  register: network_interface__loopback_result
  notify: network_interface__handler_restart_networking

- name: Save changed loopback interfaces
  set_fact:
    network_interface__loopback_changed: >-
      {{ network_interface__loopback_result.results | default([])
         | selectattr('changed')
         | map(attribute='item.device')
         | list }}

- debug: var=network_interface__loopback_changed
