---
# - name: "HACK: change `ansible_os_family` for AlmaLinux"
#   set_fact:
#     ansible_os_family: "RedHat"
#   when: ansible_os_family == "AlmaLinux"

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

# - name: Define network_pkgs.
#   set_fact:
#     network_pkgs: "{{ _network_pkgs }}"
#   when: network_pkgs is not defined

- name: Include specific tasks for the OS family
  include_tasks: "{{ ansible_os_family }}_initial.yml"

# Moved from 'ether_interfaces.yaml'
- name: Add default loopback interface
  set_fact:
    network_ether_interfaces: "{{ network_ether_interfaces + [ { 'device': network_interface_loopback_name } ] }}"
  when:
    - network_configured_interfaces_only
    - network_interface_implicit_loopback
    - "network_interface_loopback_name not in network_ether_interfaces | map(attribute='device')"

- name: Remove not needed configuration files
  import_tasks: "clean_interfaces.yml"
  when: network_configured_interfaces_only | bool


# Remove config files for interfaces with key "present: no"
- name: Remove interfaces
  include_tasks: "remove_interfaces.yaml"
  
# - name: Configure /etc/resolv.conf
#   import_tasks: "etc_resolv_conf.yaml"
#   when:
#     - ansible_os_family == "Debian"
#     - "resolvconf is not installed"
  
- name: Configure Ethernet interfaces
  import_tasks: "ether_interfaces.yml"

- name: Configure Bond interfaces
  import_tasks: "bond_interfaces.yml"
  when: network_bond_interfaces | length > 0

- name: Configure VLAN interfaces
  import_tasks: "vlan_interfaces.yml"
  when: network_vlan_interfaces | length > 0

- name: Configure Bridge interfaces
  import_tasks: "bridge_interfaces.yml"
  when: network_bridge_interfaces | length > 0
