---

- debug:
    var: "{{ item }}"
  loop:
    - network_interface_configuration_backend
    - network_interface_single_configuration_file
    - network_loopback_interfaces
    
- pause:
  when: lookup('env', 'TEST_PAUSE') | bool
    
- name: Run tasks for the selected backend
  include_tasks: "{{ network_interface_configuration_backend }}.yaml"

- name: Restart interfaces via host reboot
  block:
    - reboot:
    - setup:
  when: >-
    network_restart_interfaces | bool
    and network_interface_restart_reboot | bool
    and network_interface__configuration_changed

- name: Restart interfaces in last task in this role
  include_tasks: "{{ ansible_os_family }}_restart.yml"
  when: >-
    network_restart_interfaces | bool
    and not (network_interface_restart_reboot | bool)
    and network_interface_restart_method == 'last_task'
