---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include specific tasks for the OS family
  include_tasks: "{{ ansible_os_family }}_initial.yml"

# Moved from 'ether_interfaces.yaml'
- name: Add default loopback interface
  set_fact:
    network_ether_interfaces: "{{ network_ether_interfaces + [ { 'device': network_interface_loopback_name } ] }}"
  when:
    - network_configured_interfaces_only
    - network_interface_implicit_loopback
    - "network_interface_loopback_name not in network_ether_interfaces | map(attribute='device')"

- name: Remove not needed configuration files
  import_tasks: "clean_interfaces.yml"
  when: network_configured_interfaces_only | bool

- name: Configure Ethernet interfaces
  import_tasks: "ether_interfaces.yml"

- name: Configure Bond interfaces
  import_tasks: "bond_interfaces.yml"

- name: Configure VLAN interfaces
  import_tasks: "vlan_interfaces.yml"

- name: Configure Bridge interfaces
  import_tasks: "bridge_interfaces.yml"
  when: network_bridge_interfaces | length > 0

- set_fact:
    network_interface__all_changed_interfaces: >-
      {{ ether_interfaces_changed
         + vlan_interfaces_changed
         + bond_interfaces_changed }}


- name: Restart interfaces via host reboot
  block:
    - reboot:
    - setup:
  when: >-
    network_restart_interfaces | bool
    and network_interface_restart_reboot | bool
    and network_interface__all_changed_interfaces | length

- name: Restart interfaces in last task in this role
  include_tasks: "{{ ansible_os_family }}_restart.yml"
  when: >-
    network_restart_interfaces | bool
    and not (network_interface_restart_reboot | bool)
    and network_interface_restart_method == 'last_task'
