---
# Restart Network Interfaces (deconfigurate & reconfigurate interfaces)
- name: network_interface__handler_restart_networking
  include_tasks: "{{ ansible_os_family }}_restart.yml"
  when: >-
    network_interface_restart | bool
    and not network_interface_restart_reboot | bool
    and network_interface_restart_method == 'handlers'
