---
#Restart Network Interfaces (deconfigurate & reconfigurate interfaces)
- name: restart networking
  include_tasks: "{{ ansible_os_family }}_restart.yml"
  when:
    - network_restart_interfaces | bool
    - network_interface_restart_via_handlers | default(True) | bool
    - not network_interface_restart_reboot
