---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
platforms:
  - name: "test-ansible-role-network-interface"
    box: ${TEST_PLATFORM_BOX:-debian/buster64}
    config_options:
      synced_folder: false
    memory: 256
    cpus: 1
provisioner:
  name: ansible
  playbooks:
    converge: ../../tests/test_role_with_default_parameters.yaml
    verify: ${TEST_VERIFY_PLAYBOOK:-verify.yml}
    #verify: ../../tests/test_remove_interface_config.yaml
  # inventory:
  #   links:
  #     host_vars: host_vars
verifier:
  name: ansible
