---
- name: Converge
  hosts: all
  become: yes
  vars:
    test_backup_dir: /var/molecule_tests
  tasks:

    - name: Check backup directory
      stat:
        path: "{{ test_backup_dir }}"
      register: p

    - block:
        
        - name: Restore original network configuration
          shell: |
            rm -rf /etc/network/interfaces*
            
            cp -av {{ test_backup_dir }}/network.backup/interfaces* /etc/network

            ip route restore < {{ test_backup_dir }}/ip_route_save.bin
          when: p.stat.exists and p.stat.isdir
        
        - name: Save original network configuration
          shell: |
            mkdir -pv {{ test_backup_dir }}/network.backup
            
            cp -av /etc/network/interfaces* {{ test_backup_dir }}/network.backup/
            
            ip route save > {{ test_backup_dir }}/ip_route_save.bin
          when: not p.stat.exists
      when: >-
        ansible_os_family == "Debian"

        
    - name: Add virtual interfaces
      include_tasks: create_virtual_interface.yaml
      vars:
        type: veth
      loop:
        - veth0
        - veth1
